### PR TITLE
Fix issue #84. Update Iris logo. Changes 'VAO' to 'VO'.

### PR DESCRIPTION
**Pull request by jbudynk**

### CODE REVIEW

**Comment by jbudynk** [comment]
One issue: the logo if cutoff in the "About Me" menu. Not sure why. @olaurino, do I need to edit the PNG file, or is this is something in the About.java file that needs to be updated?

**Comment by olaurino** [comment]
Not sure I understand, I'll take a look asap.

**Comment by olaurino** [comment]
The new image has a different size, that is why the layout is compromised in the About window.

As we still have to review the About frame, this is probably OK for now, but I'd wait to test the integration of this PR with the new About window in order to merge this PR.

**Comment by olaurino** [comment]
Closing, and replacing with a new PR against new_develop.

**Pull request closed without merging**
