### PR TITLE
170 Remove obsolete code

### LINKED ISSUE #170: Remove obsolete classes and code

### PR DESCRIPTION
**Pull request by olaurino**
Resolve #170 

This PR removes obsolete and unused code both in the main source code base and in the test-components module, especially for components that had a large footprint. We can put them back at a later time if we want to.

Some of the removed classes were part of prototypes that did not turn into actual implementations and were mistakenly folded in when we were working with svn.

Some were experimental components that we shipped with Iris but that did not have enough traction and were not even documented. This applies in particular to the R component.

I tried to change the pom configuration so that jacoco excludes the test-components from the coverage analysis altogether. However, coveralls already seems to be ignoring such package, maybe because it matches a regular expression and gets ignored. In any case coveralls seems to be missing a lot of coverage anyway.

On Sonar I get a 0.6% increase in coverage (to 36.1%) which seems consistent with the amount of code removed and with the fact that the test-components were already ignored in the sonar configuration.

### CODE REVIEW

**Comment by eholum** [comment]
Merge it.

**Comment by jbudynk** [comment]
For the most part, looks good. I checked that the test-components site shows the updated information; it does.

But this testing show how quickly we should get the SAMP/sherpa-samp IT tests up and running, because there are errors in the SedStacker code that were introduced before this PR :)

I tested the SedStacker code by commenting the"@Ignore" tags in each SedStacker*Test.java. There were some errors, most likely due to the updated JUnit version and the new GUI test infrastructure.  There are some windows I expect to pop-up in the SedStacker tests; the error message shown below suggests we need to use the WindowInterceptor to handle the pop-ups. The other errors have to do with not providing tolerances in assertEquals(). Apparently this was OK in previous junit versions.

**Failing tests:**

*JUnit assertEquals():*

```
Running cfa.vo.sed.science.stacker.SedStackerNormalizerTest
java.lang.AssertionError: Use assertEquals(expected, actual, delta) to compare floating-point numbers
	at cfa.vo.sed.science.stacker.SedStackerNormalizerTest.testNormalizer(SedStackerNormalizerTest.java:270)

Running cfa.vo.sed.science.stacker.SedStackerRedshifterTest
java.lang.AssertionError: Use assertEquals(expected, actual, delta) to compare floating-point numbers
	at cfa.vo.sed.science.stacker.SedStackerRedshifterTest.testRedshifter(SedStackerRedshifterTest.java:279)

Running cfa.vo.sed.science.stacker.SedStackerStackerTest
java.lang.AssertionError: Use assertEquals(expected, actual, delta) to compare floating-point numbers
	at cfa.vo.sed.science.stacker.SedStackerStackerTest.testStacker(SedStackerStackerTest.java:268)
```
*GUI errors:*
```
testNormalizerOutsideRange(cfa.vo.sed.science.stacker.SedStackerNormalizerTest)  Time elapsed: 4.054 sec  <<< ERROR!
java.lang.Error: Unexpected window shown - this window should be handled with WindowInterceptor. 
        ....
	at cfa.vo.iris.gui.NarrowOptionPane.showMessageDialog(NarrowOptionPane.java:44)
	at cfa.vo.sed.science.stacker.SedStackerNormalizer.normalize(SedStackerNormalizer.java:229)
	at cfa.vo.sed.science.stacker.SedStackerNormalizerTest.testNormalizerOutsideRange(SedStackerNormalizerTest.java:356)

testRedshifterNoZ(cfa.vo.sed.science.stacker.SedStackerRedshifterTest)  Time elapsed: 4.023 sec  <<< ERROR!
java.lang.Error: Unexpected window shown - this window should be handled with WindowInterceptor. 
        ....
	at cfa.vo.iris.gui.NarrowOptionPane.showMessageDialog(NarrowOptionPane.java:44)
	at cfa.vo.sed.science.stacker.SedStackerRedshifter.shift(SedStackerRedshifter.java:184)
	at cfa.vo.sed.science.stacker.SedStackerRedshifter.shift(SedStackerRedshifter.java:69)
	at cfa.vo.sed.science.stacker.SedStackerRedshifterTest.testRedshifterNoZ(SedStackerRedshifterTest.java:363)
```

**Comment by jbudynk** [comment]
I think this PR is fine to merge so long as we make a task to fix the SedStacker errors.

**Comment by cxcdev** [comment]
We already have a task for that, i.e. #172. Also, this may be related to
#192 and might be addressed as part of the review for #195.

On Wed, Nov 18, 2015 at 11:42 AM, Jamie Budynkiewicz <
notifications@github.com> wrote:

> I think this PR is fine to merge so long as we make a task to fix the
> SedStacker errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChandraCXC/iris/pull/196#issuecomment-157772291>.
>



-- 
Omar Laurino
Smithsonian Astrophysical Observatory
Harvard-Smithsonian Center for Astrophysics
100 Acorn Park Dr. R-377 MS-81
02140 Cambridge, MA
(617) 495-7227

**Comment by olaurino** [comment]
We already have a task for that, i.e. #172. Also, this may be related to
#192 and might be addressed as part of the review for #195.

**Comment by eholum** [comment]
The JUnit assert stuff was fixed in https://github.com/ChandraCXC/iris/commit/bc412ec810bef649b2b0cfa08f8a0a965c84431e , still more to do for removing the @ignore flags though.

**Comment by olaurino** [comment]
Rebasing. The original tip was at  dd36181

**Pull request merged**
