### PR TITLE
142 headless configuration

### LINKED ISSUE #142: Headless Configuration
Unit/functional configuration adjusted in POMs

### PR DESCRIPTION
**Pull request by olaurino**
[release-note]
N/A
[/release-note]

Resolve #142

# Description
This is a redo of #163, after rebasing.

This PR modifies code, pom, and Travis CI configuration to run GUI tests with `UISpec4J` and in headless mode.

## POM changes
The old `NoGuiTests` profiles are removed.

New profiles have been added to the parent project to correctly configure `UISpec4j` and run the GUI tests. Note that `UISpec4j` cannot properly run on all JDKs, so the `ci-headless` profile is enabled by default for convenience.

## Code changes
`NameResolver`, which was replaced long ago by the `HarvardNameResolver` class was removed, along with its test. The test was only running without the `NoGuiTests` profile enabled and it was failing because one of the dependencies (`jel`) had been removed long ago.

The `Position` class, that was original a class nested in `NameResolver`, and that is still used by the name resolver code, has been promoted.

The only GUI test remaining, `BuilderMainViewTest`, has been updated, fixed, and moved to the `iris` package, as it will become an integration/functional test and requires access to the `Iris` class. Some test utility classes were moved to `iris-common` and can thus be used by different modules.

# Testing
The Travis CI builds pass and all the tests, including `BuilderMainViewTest`, are run:
https://travis-ci.org/ChandraCXC/iris/builds/86921024

Unfortunately there is an issue with `openjdk7` that requires a gnome package to be installed, otherwise the Java GUI components trigger the error `GLib-GIO-ERROR **: Settings schema 'org.gnome.system.proxy' is not installed`. I tested locally with `java-1.7.0-openjdk-1.7.0.75.x86_64` on `RHEL`: this should be `openjdk` but I am not sure. Tests pass.
See https://travis-ci.org/ChandraCXC/iris/builds/86919965

### CODE REVIEW

**Comment by olaurino** [comment]
Comments to PR #163 have been addressed:

* Instances of `@Ignore` now have a reason specified.
* Some tests that had mixed spaces and tabs now only have spaces for indentation (although this comes from PR #161)
* Added a simple test for the Position class, even though this class was not new code, as it was already present.
* A major refactoring, as well as new classes in iris-common and new configuration in the `POM`s now allow GUI unit tests as well as integration tests to be run from any module.

@eholum @jbudynk please let me know if this looks good to you.

**Comment by jbudynk** [comment]
Looks good.

Only minor suggestion would be to keep one copy of the resource file
"iris/src/test/resources/test_data/3c066aNED.vot" (right now, there's still
a copy of it in the sed-builder module). But if that's going to take a lot
of rewriting history, it's not worth it - the file is small. Plus, it'll be
easier to reference the file in tests for the iris module.

Thumbs up to merge it.

On Mon, Oct 26, 2015 at 5:41 PM, Omar Laurino <notifications@github.com>
wrote:

> Comments to PR #163 <https://github.com/ChandraCXC/iris/pull/163> have
> been addressed:
>
>    - Instances of @Ignore now have a reason specified.
>    - Some tests that had mixed spaces and tabs now only have spaces for
>    indentation (although this comes from PR #161
>    <https://github.com/ChandraCXC/iris/pull/161>)
>    - Added a simple test for the Position class, even though this class
>    was not new code, as it was already present.
>    - A major refactoring, as well as new classes in iris-common and new
>    configuration in the POMs now allow GUI unit tests as well as
>    integration tests to be run from any module.
>
> @eholum <https://github.com/eholum> @jbudynk <https://github.com/jbudynk>
> please let me know if this looks good to you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChandraCXC/iris/pull/164#issuecomment-151292679>.
>



-- 
Jamie A. Budynkiewicz
Smithsonian Astrophysical Observatory
Harvard-Smithsonian Center for Astrophysics
100 Acorn Park Dr. R-377 MS-81
Cambridge, MA 02140

**Comment by olaurino** [comment]
@eholum do you think I can merge this or do you have more comments?

**Comment by eholum** [comment]
Merge it.

**Pull request merged**
