### PR TITLE
Sprint 5 Merge PR

### PR DESCRIPTION
**Pull request by eholum**
This PR closes:

https://github.com/ChandraCXC/iris-dev/issues/5
https://github.com/ChandraCXC/iris-dev/issues/8
https://github.com/ChandraCXC/iris-dev/issues/23
ChandraCXC/iris-dev#14
ChandraCXC/iris-dev#6

with PRs:

https://github.com/ChandraCXC/iris/pull/255 
https://github.com/ChandraCXC/iris/pull/254
https://github.com/ChandraCXC/iris/pull/253
https://github.com/ChandraCXC/iris/pull/260
https://github.com/ChandraCXC/iris/pull/257

### CODE REVIEW

**Comment by jbudynk** [comment]
I'll give a better, summarized comment after I'm finished reviewing, but for now I'm just listing any issues I find.

1.  I can't scroll left-to-right on the Metadata Browser.
2.  It would be nice if the Metadata Browser columns were wide enough to see the full column title, or better yet, the longest entry in that column, instead of the column widths being truncated to fit within the initial width of the table.  Though I'd be happy if we did this for at least the flux, spectral, and error columns.

**Comment by eholum** [comment]
We also need to do something with the legend on the plotter - maybe just pull it off into it's own little location in the plot view? Right now it's not visible.

**Comment by eholum** [comment]
Merged color selection https://github.com/ChandraCXC/iris/pull/260

**Comment by eholum** [comment]
Merged iris star tables https://github.com/ChandraCXC/iris/pull/260

**Comment by jbudynk** [comment]
Giving the OK to merge into master

**Comment by jbudynk** [comment]
Tests done before merging (on OS X):

- ran `mvn verify` successfully
- open Iris with Test Builder (`./Iris --test &`)
- add NED SED and User Segment from Test Builder.
  - Verified that there are two segments on the plot with the same Target name, in two different colors
  - In Metadata Browser, I can switch between the two segments. The columns for each segment in the table update as expected when switching.
- Can save the full SED as VOT and reload it into Iris
- pan/zoom on plotter

Issues that should be fixed and have not been assigned as a task yet:
- scrolling horizontally in the Metadata Browser tables
- increasing the width of the Metadata Browser column names automatically
- legend location on plot window

**Pull request merged**
